"""
Subtask 1.7b — complete the 32-class in-distribution baseline.

Runs model.val() on the held-out test split (data/merged/images/test/, 1428 tiles)
and writes all 32 per-class AP@50 / AP@50-95 / recall values to
docs/class_identity/phase1_baseline_ap.json, overwriting the partial 8-class
transcription from docs/phase1_analysis.md.

Usage:
    PYTHONPATH=src python scripts/update_baseline.py [--weights ...] [--device ...]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, "src")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Write full 32-class AP baseline to phase1_baseline_ap.json")
    parser.add_argument("--weights", default="runs/detect/train/weights/best.pt")
    parser.add_argument("--data",    default="configs/yolo_baseline.yaml")
    parser.add_argument("--imgsz",   type=int,   default=640)
    parser.add_argument("--conf",    type=float, default=0.25)
    parser.add_argument("--iou",     type=float, default=0.6)
    parser.add_argument("--device",  default="")
    parser.add_argument("--out",     default="docs/class_identity/phase1_baseline_ap.json")
    args = parser.parse_args()

    weights = Path(args.weights)
    if not weights.exists():
        sys.exit(f"[error] weights not found: {weights}")
    data_yaml = Path(args.data)
    if not data_yaml.exists():
        sys.exit(f"[error] data yaml not found: {data_yaml}")

    import yaml
    from ultralytics import YOLO
    print(f"Loading model: {weights}")
    model = YOLO(str(weights))
    # Use verified names from the config YAML (model.names has the old training-time
    # guessed names baked into the weights; the YAML was updated in subtask 1.6a).
    with open(data_yaml) as f:
        cfg = yaml.safe_load(f)
    names: dict[int, str] = {int(k): v for k, v in cfg["names"].items()}

    print(f"Running model.val() on {data_yaml} (split=test) …")
    save_dir = weights.parent.parent / "eval_baseline"
    save_dir.mkdir(parents=True, exist_ok=True)

    metrics = model.val(
        data=str(data_yaml),
        split="test",
        imgsz=args.imgsz,
        conf=args.conf,
        iou=args.iou,
        device=args.device,
        save_dir=str(save_dir),
        plots=False,
        verbose=False,
    )

    box = metrics.box

    # ── build per-class dict ───────────────────────────────────────────────────
    by_index: dict[str, dict] = {}
    for rank, cls_idx in enumerate(map(int, box.ap_class_index)):
        by_index[str(cls_idx)] = {
            "name":    names[cls_idx],
            "ap50":    round(float(box.ap50[rank]), 6),
            "ap50_95": round(float(box.ap[rank]),   6),
            "recall":  round(float(box.r[rank]),    6),
        }

    out_data = {
        "_comment": (
            "Full 32-class in-distribution baseline from model.val() on "
            "data/merged test split (1428 tiles). Generated by "
            "scripts/update_baseline.py (subtask 1.7b). Supersedes the "
            "partial 8-class transcription from docs/phase1_analysis.md."
        ),
        "overall": {
            "map50":     round(float(box.map50), 6),
            "map50_95":  round(float(box.map),   6),
            "precision": round(float(box.mp),    6),
            "recall":    round(float(box.mr),    6),
        },
        "by_index": dict(sorted(by_index.items(), key=lambda kv: int(kv[0]))),
    }

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(out_data, indent=2) + "\n", encoding="utf-8")
    print(f"\nWritten: {out_path}  ({len(by_index)} classes)")

    # ── print worst-first table ────────────────────────────────────────────────
    rows = sorted(by_index.items(), key=lambda kv: kv[1]["ap50"])
    col_w = max(len(v["name"]) for v in by_index.values()) + 2

    print("\n" + "=" * (col_w + 46))
    print("32-class in-distribution AP  (worst AP@50 first)")
    print("=" * (col_w + 46))
    header = f"{'idx':>4}  {'Class':<{col_w}}  {'AP@50':>8}  {'AP@50-95':>10}  {'Recall':>8}"
    print(header)
    print("-" * len(header))
    for idx_str, v in rows:
        print(f"{int(idx_str):>4}  {v['name']:<{col_w}}  "
              f"{v['ap50']:>8.4f}  {v['ap50_95']:>10.4f}  {v['recall']:>8.4f}")
    print("=" * len(header))
    print(f"\nOverall  mAP@50={out_data['overall']['map50']:.4f}  "
          f"mAP@50-95={out_data['overall']['map50_95']:.4f}  "
          f"P={out_data['overall']['precision']:.4f}  "
          f"R={out_data['overall']['recall']:.4f}")


if __name__ == "__main__":
    main()
